baseURL = 'https://rznrex.github.io/rzn-blog.github.io/'
languageCode = 'zh-cn'
title = '我的个人博客'
theme = "PaperMod"

[params]
  mainSections = ["posts"]

  [params.homeInfoParams]
    Title = "你好，我是 rznrex"
    Content = "欢迎来到我的个人博客，这里记录着我的思考和成长。"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/rznrex"

[paginate]
  paginate = 6